version: 0.1.0.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration:
- Release
- Release.Signed

environment:
  AppVeyor: APPVEYOR

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
- path: ClosedXML.Report/bin/%CONFIGURATION%/net45/ClosedXML.Report.dll
